// Pulls names, types, base stats, height and weight for the original 151 from PokeAPI.
import { writeFileSync } from 'node:fs';
const nice = { 'nidoran-f': 'Nidoran♀', 'nidoran-m': 'Nidoran♂', 'mr-mime': 'Mr. Mime', farfetchd: "Farfetch'd" };
const out = [];
for (let start = 1; start <= 151; start += 25) {
  const ids = Array.from({ length: Math.min(25, 152 - start) }, (_, i) => start + i);
  const rows = await Promise.all(ids.map(async (id) => {
    const p = await (await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`)).json();
    const s = Object.fromEntries(p.stats.map((x) => [x.stat.name, x.base_stat]));
    return {
      id, name: nice[p.name] || p.name[0].toUpperCase() + p.name.slice(1),
      types: p.types.map((t) => t.type.name),
      hp: s.hp, atk: s.attack, def: s.defense, spa: s['special-attack'], spd: s['special-defense'], spe: s.speed,
      h: p.height, w: p.weight,
    };
  }));
  out.push(...rows);
}
writeFileSync(new URL('../js/data.js', import.meta.url),
  '// Generated by tools/fetch-data.mjs\n(globalThis.PG = globalThis.PG || {}).MONS = [\n' + out.map((r) => '  ' + JSON.stringify(r)).join(',\n') + '\n];\n');
console.log(out.length, 'written');
